# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tf-state-konvoloka"
    dynamodb_table = "tf-lock-table-konvoloka"
    encrypt        = false
    key            = "./terraform.tfstate"
    region         = "ap-southeast-1"
  }
}
